"""Seed demo data for new users.

Usage:
    cd backend && source venv/bin/activate
    python -m app.scripts.seed_demo

Creates:
    - 1 admin user (admin@opendocx.local / admin123)
    - 1 demo project "Welcome to OpenDocX" with default version v1.0
    - 2 sample documents:
        * getting-started.md (intro to OpenDocX features)
        * ai-floating-tip-demo.md (showcase AI floating tip)
    - 1 default feedback template (empty)

This data is COMPLETELY isolated from Wang Liu's local data
(Admin的 64 章内容 + 9 项目 + 9 篇文章 全部在他本地 DB, 不在此脚本范围内).
"""
import asyncio
import sys
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.user import User
from app.models.project import Project
from app.models.version import Version
from app.models.document import Document
from app.utils.auth import hash_password


# Compatibility: PostgreSQL TIMESTAMP WITHOUT TIME ZONE 列要 naive datetime
# (OpenAtlas P3.11 Bug 9 同源, R9 fix 统一用 .replace(tzinfo=None))
def _now() -> datetime:
    """Naive UTC datetime for TIMESTAMP WITHOUT TIME ZONE columns."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


# ===== Demo data constants =====

DEMO_ADMIN_EMAIL = "admin@opendocx.local"
DEMO_ADMIN_PASSWORD = "admin123"  # noqa: S105  - 公开 demo 凭据, README 写明

DEMO_PROJECT_NAME = "Welcome to OpenDocX"
DEMO_PROJECT_SLUG = "welcome-to-opendocx"
DEMO_PROJECT_DESC = "A demo project showcasing OpenDocX's core features. "\
    "Edit me, build me, or delete me - this is your playground."

DEMO_VERSION_NAME = "v1.0"
DEMO_VERSION_DESC = "Default demo version"

GETTING_STARTED_CONTENT = """# Getting Started with OpenDocX

Welcome to your OpenDocX demo project! This is a **playground** to explore
OpenDocX's core features.

## Try these:

### 1. AI Floating Tip
**Select any text below** to summon the AI floating tip (look for the small
icon near your selection). You can ask the AI to:
- Summarize this section
- Translate to English
- Explain in simpler terms
- Answer a question about the selection

### 2. Pre-Build Modal
Click the "Build" button in the top right. You'll see a pre-build confirmation
modal showing all your documents, with stats and one-click publish options
for drafts.

### 3. Static Site Generation
Click "Build" again (or "Start Build" in the modal) to generate a complete
static site from your database. Find the output in `data/builds/`.

### 4. Command Palette
Press `Cmd+K` (or `Ctrl+K` on Windows/Linux) to open the command palette.
Search for projects, docs, or jump to settings.

### 5. Dark Mode
Click your avatar in the top right, then toggle theme.

## Markdown Support

OpenDocX supports:
- **GFM** (GitHub Flavored Markdown): tables, task lists, strikethrough
- **Code blocks** with syntax highlighting (13 languages)
- **Mermaid** diagrams
- **Admonitions** (Note/Warning/Tip/Danger/Info blocks)
- **Math** (KaTeX, optional)

## What's Next?

- Edit this document and see live preview
- Create a new document in the sidebar
- Build a static site and explore `data/builds/welcome-to-opendocx/v1.0/`
- Delete this project (it won't affect your other data)

Have fun!
"""

AI_TIP_DEMO_CONTENT = """# AI Floating Tip Demo

This document showcases the AI floating tip. Try selecting any paragraph below
and watch the AI tip appear.

## What is the AI Floating Tip?

The AI floating tip is a small popup that appears when you select text in the
editor. It offers 6 quick AI operations:
1. **Summarize** - Get a concise summary of the selection
2. **Expand** - Add more detail
3. **Translate** - Convert to English (or another language)
4. **Q&A** - Ask a question about the selection
5. **Analyze** - Deep analysis of the content
6. **Rewrite** - Improve clarity and style

## How to use it

1. **Select text** with your mouse (drag to highlight)
2. **Wait** for the small icon to appear near your selection
3. **Click** the icon or press the hotkey
4. **Choose** an operation from the menu
5. **Watch** the AI response stream in real-time (SSE)
6. **Accept** to replace the original text, or **Reject** to discard

## Example Selection

Try selecting this paragraph:

> "OpenDocX uses Server-Sent Events (SSE) for real-time AI responses. This means
> tokens appear in the response panel as they're generated by the LLM, giving
> you a ChatGPT-like streaming experience."

After selecting, click the icon and choose "Summarize" to see OpenDocX compress
this paragraph into a single sentence.

## Privacy

Your selection text is sent to your configured LLM provider (OpenAI,
Anthropic, Xiaomi mimo, etc.) for processing. Check `.env` for your
`LLM_BASE_URL` configuration.
"""


# ===== Seed functions =====


async def seed_admin(db: AsyncSession) -> User:
    """Create or get demo admin user."""
    result = await db.execute(
        select(User).where(User.email == DEMO_ADMIN_EMAIL)
    )
    admin = result.scalar_one_or_none()
    if admin:
        print(f"  - admin user already exists: {admin.email}")
        return admin

    admin = User(
        email=DEMO_ADMIN_EMAIL,
        name="OpenDocX Admin",
        password_hash=hash_password(DEMO_ADMIN_PASSWORD),
        role="admin",
        is_active=True,
    )
    db.add(admin)
    await db.flush()
    print(f"  + created admin: {admin.email} / {DEMO_ADMIN_PASSWORD}")
    return admin


async def seed_project(db: AsyncSession, admin: User) -> Project:
    """Create or get demo project."""
    result = await db.execute(
        select(Project).where(Project.slug == DEMO_PROJECT_SLUG)
    )
    project = result.scalar_one_or_none()
    if project:
        print(f"  - project already exists: {project.name}")
        return project

    project = Project(
        name=DEMO_PROJECT_NAME,
        slug=DEMO_PROJECT_SLUG,
        description=DEMO_PROJECT_DESC,
        created_by=admin.id,
        created_at=_now(),
    )
    db.add(project)
    await db.flush()
    print(f"  + created project: {project.name}")
    return project


async def seed_version(db: AsyncSession, project: Project) -> Version:
    """Create or get default version v1.0."""
    result = await db.execute(
        select(Version).where(
            Version.project_id == project.id,
            Version.version == DEMO_VERSION_NAME,
        )
    )
    version = result.scalar_one_or_none()
    if version:
        print(f"  - version already exists: {version.version}")
        return version

    version = Version(
        project_id=project.id,
        version=DEMO_VERSION_NAME,
        is_default=True,
        created_at=_now(),
    )
    db.add(version)
    await db.flush()
    print(f"  + created version: {version.version}")
    return version


async def seed_documents(
    db: AsyncSession, version: Version, admin: User
) -> None:
    """Create 2 demo documents."""
    docs_to_seed = [
        {
            "slug": "getting-started",
            "title": "Getting Started with OpenDocX",
            "content": GETTING_STARTED_CONTENT,
            "sort_order": 1,
        },
        {
            "slug": "ai-floating-tip-demo",
            "title": "AI Floating Tip Demo",
            "content": AI_TIP_DEMO_CONTENT,
            "sort_order": 2,
        },
    ]

    for doc_data in docs_to_seed:
        result = await db.execute(
            select(Document).where(
                Document.version_id == version.id,
                Document.slug == doc_data["slug"],
            )
        )
        doc = result.scalar_one_or_none()
        if doc:
            print(f"  - doc already exists: {doc_data['title']}")
            continue

        doc = Document(
            version_id=version.id,
            created_by=admin.id,
            slug=doc_data["slug"],
            title=doc_data["title"],
            content=doc_data["content"],
            status="published",
            sort_order=doc_data["sort_order"],
            created_at=_now(),
            updated_at=_now(),
        )
        db.add(doc)
        print(f"  + created doc: {doc_data['title']}")

    await db.flush()


# ===== Main =====


async def main() -> None:
    print("=" * 60)
    print("OpenDocX Demo Data Seeder")
    print("=" * 60)
    print()
    print("This script creates demo data in your LOCAL database.")
    print("Wang Liu's production data is NOT affected.")
    print()

    async for db in get_db():
        try:
            print("[1/4] Seeding admin user...")
            admin = await seed_admin(db)

            print("[2/4] Seeding demo project...")
            project = await seed_project(db, admin)

            print("[3/4] Seeding default version...")
            version = await seed_version(db, project)

            print("[4/4] Seeding sample documents...")
            await seed_documents(db, version, admin)

            await db.commit()
            print()
            print("=" * 60)
            print("Demo data seeded successfully!")
            print("=" * 60)
            print()
            print("Next steps:")
            print(f"  1. Start backend: bash backend/scripts/start-backend.sh")
            print(f"  2. Start frontend: cd frontend && npx vite --port 3077")
            print(f"  3. Open: http://localhost:3077")
            print(f"  4. Login: {DEMO_ADMIN_EMAIL} / {DEMO_ADMIN_PASSWORD}")
            print()

        except Exception as e:
            await db.rollback()
            print(f"\nERROR: {e}", file=sys.stderr)
            raise
        finally:
            await db.close()


if __name__ == "__main__":
    asyncio.run(main())
